# This is a basic workflow that is manually triggered

name: Maven Publish workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'local.properties'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publishMaven:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # STEP - 1 Checkout current repo [powerplay_kmp]
    - name: Checkout source repository
      uses: actions/checkout@v4
      with: 
        repository: Deepakgoyal-iOS/powerplay_kmp
        token: ${{ secrets.GIT_TOKEN }}
      
    # STEP - 2 Build XCFramework task for creating XCFramework file.
    - name: Read current version
      id: read
      run: |
          VERSION=$(grep "^version=" local.properties | cut -d'=' -f2)
          VERSION_TYPE=$(grep "^bump-version-type = " gradle/libs.versions.toml | cut -d'=' -f2 | tr -d ' "')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "versionType=$VERSION_TYPE" >> $GITHUB_OUTPUT
      
    # STEP - 3 Checkout package repo [XCPowerplayKMP]
    - name: Increment version
      id: bump
      run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.read.outputs.version }}"
          VERSION_TYPE="${{ steps.read.outputs.versionType }}"

          if [ "$VERSION_TYPE" = "0" ]; then
            echo "Major bump"
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0

          elif [ "$VERSION_TYPE" = "1" ]; then
            echo "Minor bump"
            MINOR=$((MINOR + 1))
            PATCH=0

          else
            echo "Patch bump"
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          sed -i "s/^version=.*/version=$NEW_VERSION/" local.properties
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

    # STEP - 4 Publish maven to github packages
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        VERSION: ${{ steps.bump.outputs.version }}
      run: |
          ./gradlew publishAndroidReleasePublicationToGitHubPackagesRepository

      # STEP - 5 Commit & Push incremented version
    - name: Commit and push
      run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add local.properties
          git commit -m "Automated: bump version to ${{ steps.bump.outputs.version }}" || echo "No changes to commit"
          git push
      
